export const browserCoreExamples = [
  "razroom browser status",
  "razroom browser start",
  "razroom browser stop",
  "razroom browser tabs",
  "razroom browser open https://example.com",
  "razroom browser focus abcd1234",
  "razroom browser close abcd1234",
  "razroom browser screenshot",
  "razroom browser screenshot --full-page",
  "razroom browser screenshot --ref 12",
  "razroom browser snapshot",
  "razroom browser snapshot --format aria --limit 200",
  "razroom browser snapshot --efficient",
  "razroom browser snapshot --labels",
];

export const browserActionExamples = [
  "razroom browser navigate https://example.com",
  "razroom browser resize 1280 720",
  "razroom browser click 12 --double",
  'razroom browser type 23 "hello" --submit',
  "razroom browser press Enter",
  "razroom browser hover 44",
  "razroom browser drag 10 11",
  "razroom browser select 9 OptionA OptionB",
  "razroom browser upload /tmp/razroom/uploads/file.pdf",
  'razroom browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "razroom browser dialog --accept",
  'razroom browser wait --text "Done"',
  "razroom browser evaluate --fn '(el) => el.textContent' --ref 7",
  "razroom browser console --level error",
  "razroom browser pdf",
];
