#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${RAZROOM_INSTALL_E2E_IMAGE:-${RAZROOM_INSTALL_E2E_IMAGE:-razroom-install-e2e:local}}"
INSTALL_URL="${RAZROOM_INSTALL_URL:-${RAZROOM_INSTALL_URL:-https://razroom.bot/install.sh}}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
RAZROOM_E2E_MODELS="${RAZROOM_E2E_MODELS:-${RAZROOM_E2E_MODELS:-}}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker/install-sh-e2e"

echo "==> Run E2E installer test"
docker run --rm \
  -e RAZROOM_INSTALL_URL="$INSTALL_URL" \
  -e RAZROOM_INSTALL_TAG="${RAZROOM_INSTALL_TAG:-${RAZROOM_INSTALL_TAG:-latest}}" \
  -e RAZROOM_E2E_MODELS="$RAZROOM_E2E_MODELS" \
  -e RAZROOM_INSTALL_E2E_PREVIOUS="${RAZROOM_INSTALL_E2E_PREVIOUS:-${RAZROOM_INSTALL_E2E_PREVIOUS:-}}" \
  -e RAZROOM_INSTALL_E2E_SKIP_PREVIOUS="${RAZROOM_INSTALL_E2E_SKIP_PREVIOUS:-${RAZROOM_INSTALL_E2E_SKIP_PREVIOUS:-0}}" \
  -e OPENAI_API_KEY="$OPENAI_API_KEY" \
  -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  -e ANTHROPIC_API_TOKEN="$ANTHROPIC_API_TOKEN" \
  "$IMAGE_NAME"
